export const EVENT_TYPE_SITE_CREATED = 'SITE_CREATED';

export const EVENT_TYPE_DATE_OVERRIDE_SET = 'DATE_OVERRIDE_SET';
export const EVENT_TYPE_DATE_OVERRIDE_UPDATED = 'DATE_OVERRIDE_UPDATED';
export const EVENT_TYPE_DATE_OVERRIDE_CLEARED = 'DATE_OVERRIDE_CLEARED';

export const EVENT_TYPE_DSD_SITE_DISCOVERED = 'DSD_SITE_DISCOVERED';
export const EVENT_TYPE_SITE_HEALTHY = 'SITE_HEALTHY';
export const EVENT_TYPE_SITE_DOWN = 'SITE_DOWN';
export const EVENT_TYPE_SITE_RECOVERED = 'SITE_RECOVERED';
export const EVENT_TYPE_DSD_SERVER_CHANGED = 'DSD_SERVER_CHANGED';
export const EVENT_TYPE_DSD_IP_CHANGED = 'DSD_IP_CHANGED';
export const EVENT_TYPE_DOMAIN_EXPIRATION_CHANGED = 'DOMAIN_EXPIRATION_CHANGED';

export const APP_NAME = 'LOW';
export const APP_FULL_NAME = 'The Life of Websites';

export const AUTH_COOKIE_NAME = 'low_session';
export const SESSION_TTL_SECONDS = 60 * 60 * 24 * 14;

export const DSD_SYNC_JOB_TYPE = 'manual_full_sync';
